# Run unit tests and build release
name: PR Integration Test
on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened, edited, ready_for_review]
  push:
    branches:
      - gh-readonly-queue/main/**
      - gh-readonly-queue/master/**

env:
  LC_ALL: "en_US.UTF-8"
  LANG: "en_US.UTF-8"

jobs:
  check-title:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.21

    - name: Download Dependencies
      run: go get github.com/jdkato/prose/v2

    - name: Check PR title for imperative mood
      if: github.event_name == 'pull_request'
      run: go run .github/scripts/check-pr-title-imperative-mood.go "${{ github.event.pull_request.title }}"

    - name: Check PR title for imperative mood
      if: github.event_name == 'push'
      run: go run .github/scripts/check-pr-title-imperative-mood.go "${{ github.event.pull_request.title }}"